# Generated by Django 4.0.3 on 2022-03-30 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('imagePath', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('square', models.FloatField()),
                ('floor', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('contacts', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppliancesFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridge', models.BooleanField(blank=True)),
                ('microwave', models.BooleanField(blank=True)),
                ('washMachine', models.BooleanField(blank=True)),
                ('oven', models.BooleanField(blank=True)),
                ('conditioner', models.BooleanField(blank=True)),
                ('router', models.BooleanField(blank=True)),
                ('TV', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20)),
                ('floors', models.IntegerField(blank=True)),
                ('heating', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoPath', models.CharField(max_length=255)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.alarm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(height_field=200, upload_to='', width_field=200)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliances', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='estate.appliancesfilters')),
                ('house', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='estate.housefilters')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='filters',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='estate.filters'),
        ),
    ]
