# Generated by Django 4.0.3 on 2022-03-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housefilters',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Панельный'), (2, 'Кирпичный'), (3, 'Монолитный')], verbose_name='Тип_дома'),
        ),
    ]
