# Generated by Django 4.0.3 on 2022-03-31 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_alter_housefilters_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='imagePath',
        ),
        migrations.AlterField(
            model_name='appliancesfilters',
            name='TV',
            field=models.BooleanField(blank=True, verbose_name='Телевизор'),
        ),
        migrations.AlterField(
            model_name='appliancesfilters',
            name='conditioner',
            field=models.BooleanField(blank=True, verbose_name='Кондиционер'),
        ),
        migrations.AlterField(
            model_name='appliancesfilters',
            name='fridge',
            field=models.BooleanField(blank=True, verbose_name='Холодильник'),
        ),
        migrations.AlterField(
            model_name='appliancesfilters',
            name='microwave',
            field=models.BooleanField(blank=True, verbose_name='Микроволновка'),
        ),
        migrations.AlterField(
            model_name='appliancesfilters',
            name='oven',
            field=models.BooleanField(blank=True, verbose_name='Печь'),
        ),
        migrations.AlterField(
            model_name='appliancesfilters',
            name='router',
            field=models.BooleanField(blank=True, verbose_name='Роутер'),
        ),
        migrations.AlterField(
            model_name='appliancesfilters',
            name='washMachine',
            field=models.BooleanField(blank=True, verbose_name='Стиральная машина'),
        ),
        migrations.AlterField(
            model_name='housefilters',
            name='floors',
            field=models.IntegerField(blank=True, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='housefilters',
            name='heating',
            field=models.CharField(blank=True, max_length=20, verbose_name='Вид отопления'),
        ),
        migrations.AlterField(
            model_name='housefilters',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Панельный'), (2, 'Кирпичный'), (3, 'Монолитный')], verbose_name='Тип дома'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='image',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.announcement'),
        ),
    ]
