# Generated by Django 4.0.3 on 2022-03-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_image_remove_announcement_imagepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housefilters',
            name='heating',
            field=models.IntegerField(blank=True, choices=[(1, 'Отопление тёплыми полами'), (2, 'Водяное'), (1, 'Воздушное'), (1, 'Паровое')], verbose_name='Вид отопления'),
        ),
    ]
