# Generated by Django 4.0.3 on 2022-03-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_alter_housefilters_heating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='square',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='appliances',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='house',
        ),
        migrations.AddField(
            model_name='filters',
            name='TV',
            field=models.BooleanField(default=False, verbose_name='Телевизор'),
        ),
        migrations.AddField(
            model_name='filters',
            name='conditioner',
            field=models.BooleanField(default=False, verbose_name='Кондиционер'),
        ),
        migrations.AddField(
            model_name='filters',
            name='floor',
            field=models.IntegerField(blank=True, default=0, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='filters',
            name='floors',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество этажей'),
        ),
        migrations.AddField(
            model_name='filters',
            name='fridge',
            field=models.BooleanField(default=False, verbose_name='Холодильник'),
        ),
        migrations.AddField(
            model_name='filters',
            name='heating',
            field=models.IntegerField(blank=True, choices=[(1, 'Отопление тёплыми полами'), (2, 'Водяное'), (3, 'Воздушное'), (4, 'Паровое')], default=0, verbose_name='Вид отопления'),
        ),
        migrations.AddField(
            model_name='filters',
            name='microwave',
            field=models.BooleanField(default=False, verbose_name='Микроволновка'),
        ),
        migrations.AddField(
            model_name='filters',
            name='oven',
            field=models.BooleanField(default=False, verbose_name='Печь'),
        ),
        migrations.AddField(
            model_name='filters',
            name='router',
            field=models.BooleanField(default=False, verbose_name='Роутер'),
        ),
        migrations.AddField(
            model_name='filters',
            name='square',
            field=models.FloatField(blank=True, default=0, verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='filters',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Панельный'), (2, 'Кирпичный'), (3, 'Монолитный')], default=0, verbose_name='Тип дома'),
        ),
        migrations.AddField(
            model_name='filters',
            name='washMachine',
            field=models.BooleanField(default=False, verbose_name='Стиральная машина'),
        ),
        migrations.DeleteModel(
            name='AppliancesFilters',
        ),
        migrations.DeleteModel(
            name='HouseFilters',
        ),
    ]
